### ISSUE TITLE
WTFPL

### ISSUE THREAD

**Issue by redstoneguy12** [fabric-community/bikehouse#1]
It should have the WTFPL

**Comment by snakefangox** [comment]
WTFPL doesn't support Germany use cases. CC0 is clearly the better choice.

**Comment by Ueaj-Kerman** [comment]
we should go with ARR

**Comment by ramidzkh** [comment]
https://cdn.discordapp.com/attachments/608088354042544139/673330966152085525/unknown.png

**Comment by Ueaj-Kerman** [comment]
![image](https://user-images.githubusercontent.com/28693059/87731886-226d5f80-c791-11ea-92dd-26dd74daaa52.png)

**Comment by Ueaj-Kerman** [comment]
and yes, it should be LICENCE.png, not in text

**Comment by snakefangox** [comment]
I concur

**Comment by Azzyypaaras** [comment]
Nonononono bad bad bad pngs are the b ig stinky owo baddies, clearly this should be an obfuscated LICENCE.jar that you need to decompile to read.
